# Generated by Django 4.1.4 on 2022-12-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(choices=[('None', 'None'), ('teacheradmin', 'teacheradmin'), ('studentadmin', 'studentadmin')], default='None', max_length=100),
        ),
    ]
